# -*- coding: utf-8 -*-

Automatically generated by Colab.

#This code calculates the accessibility of settlements to amenities in a rural municipality. 
#I. Data needed
#The user provides :
#- the centres of settlements in .shp,
#- the points of interest (services) in .shp,
#- the gtfs file of the bus routes for the area of interest.

#The boundaries of the settlements are obtained automatically by OSM,
#The road network is automatically downloaded from the OSM after the user enters the coordinates of a polygonal area of interest.#

#II. Accessibility calculation
#Next, the accessibility of settlements to points of interest (amenities) is calculated.

# **CONNECION WITH GOOGLE DRIVE**
"""

#Connect with Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""# **DOWNLOAD AND IMPORT LIBRARIES**"""

#Download Libraries
!pip install geopandas
!pip install networkx
!pip install osmnx
!pip install geopandas partridge shapely folium
!pip install geopandas transliterate
!pip install partridge pandas

#Import Libraries
import geopandas as gpd
import networkx as nx
import osmnx as ox
from shapely.geometry import Point, Polygon
import pandas as pd
import partridge as ptg
import os
from shapely.geometry import Point, LineString
from transliterate import translit
import matplotlib.pyplot as plt
import numpy as np
import itertools

"""# **READ CITY CENTERS FROM GOOGLE DRIVE**"""

# Load the shapefile with city centers
city_centers_init = gpd.read_file('/content/drive/My Drive/oikismoi_amari.shp')

# Sort the city_centers based on names of cities
city_centers = city_centers_init.sort_values(by="name_en", ascending=True)

# Print city_centers
print(city_centers)

# Convert greek characters to english
# Define the column with Greek characters, e.g., 'Greek_Column'
greek_column = 'TOP_KOIN'

# Transliterate Greek characters to English in the specified column
city_centers[greek_column] = city_centers[greek_column].apply(lambda x: translit(x, 'el', reversed=True) if isinstance(x, str) else x)

"""# **DOWNLOAD ROAD NETWORK FROM OSM**"""

# Define your area of interest as a polygon using coordinates (longitude, latitude)
# Example: a rough square polygon
area_polygon = Polygon([
    (24.5430, 35.3081),
    (24.5430, 35.0982),
    (24.8142, 35.0982),
    (24.8142, 35.3081)
])

# Download the road network for the area inside the polygon
G = ox.graph_from_polygon(area_polygon, network_type='all')

# Convert the road network to a GeoDataFrame for nodes and edges
nodes, edges = ox.graph_to_gdfs(G)

# Save the edges (road network) to a shapefile
edges.to_file('road_network.shp')

# Plot the graph (road network)
ox.plot_graph(G)
plt.show()

"""# **SET SPEED AND DISTANCE**"""

# Set walking speed (meters per minute)
walking_speed = 80  # average walking speed: 80 meters/minute
time_limit = 15  # walking time in minutes
distance_limit = walking_speed * time_limit  # 15-minute walk = 1200 meters

# Get the CRS of the road network and project the city centers to match it
nodes, edges = ox.graph_to_gdfs(G)
road_network_crs = nodes.crs  # Get the CRS of the nodes GeoDataFrame
city_centers = city_centers.to_crs(road_network_crs)

print(city_centers.crs)

"""# **CREATE ISOCHRONES AROUND CITY CENTERS**"""

# Function to calculate isochrone from each city center point
isochrones = []

for idx, city in city_centers.iterrows():
    # Get the city center point as (latitude, longitude)
    center_point = (city.geometry.y, city.geometry.x)

    # Find the nearest road network node to the city center
    nearest_node = ox.distance.nearest_nodes(G, X=center_point[1], Y=center_point[0])

    # Create subgraph of all reachable nodes within the walking distance (1200 meters)
    subgraph = nx.ego_graph(G, nearest_node, radius=distance_limit, distance='length')

    # Get node coordinates (x, y) for the reachable nodes
    node_points = [Point(data['x'], data['y']) for node, data in subgraph.nodes(data=True)]

    if node_points:
        # Create a GeoSeries of node points and compute the convex hull to get a polygon
        isochrone_polygon = gpd.GeoSeries(node_points).unary_union.convex_hull

        # Ensure that the geometry is a Polygon
        if isinstance(isochrone_polygon, Polygon):
            # Append the result as a dictionary with city name and geometry
            isochrones.append({'city': city['name_en'], 'geometry': isochrone_polygon})

# Convert list of isochrones to a GeoDataFrame
isochrones_gdf = gpd.GeoDataFrame(isochrones, crs=city_centers.crs)

# Plot the isochrones
isochrones_gdf.plot()

# Save the isochrones to a shapefile
isochrones_gdf.to_file('15_minute_walking_isochrones.shp')

"""# **SELECT POI WITHIN ISOCHRONES**"""

# Load the isochrones polygons and read points of interest from Google Drive
gdf_polygons = gpd.read_file('/content/15_minute_walking_isochrones.shp')
gdf_points = gpd.read_file('/content/drive/My Drive/new_pois_amari.shp')

# Convert to WGS84 (EPSG:4326)
gdf_points_wgs84 = gdf_points.to_crs(epsg=4326)
# Convert to WGS84 (EPSG:4326)
gdf_polygons_wgs84 = gdf_polygons.to_crs(epsg=4326)

# Ensure both layers are in the same CRS
if gdf_polygons.crs != gdf_points.crs:
    gdf_polygons = gdf_polygons.to_crs(gdf_points.crs)

# Save the converted points to a new shapefile
gdf_points_wgs84.to_file('converted_poi_wgs84.shp')

# Find points that are within the polygons
points_within_polygons = gdf_points[gdf_points.geometry.apply(lambda point: any(point.within(polygon) for polygon in gdf_polygons.geometry))]

# Check if there are any points found
if not points_within_polygons.empty:
    print(f"Number of points found: {len(points_within_polygons)}")

    # Save the filtered points that are within polygons to a new shapefile
    points_within_polygons.to_file('points_within_polygons.shp', driver='ESRI Shapefile')

else:
    print("No points were found within the polygons.")

# Load the shapefiles of isochrones polygons
isochrones = gdf_polygons

services = gpd.read_file('/content/points_within_polygons.shp')

# Ensure the CRS matches between both GeoDataFrames
services = services.to_crs(isochrones.crs)

# Check for null values in the village names column
print(isochrones['city'].isnull().sum())  # Adjust 'city' to your column name
print(isochrones['city'].unique())  # To see all unique names, including None

# Fill null values with a placeholder (optional)
isochrones['city'] = isochrones['city'].fillna('Unknown Village')

# Perform the spatial join
joined_data = gpd.sjoin(services, isochrones, predicate='within', how='right')

# Group by village name and count the services
service_counts = (
    joined_data.groupby('city')['Name']  # Replace 'city' with the actual village name column
    .count()
    .reindex(isochrones['city'].unique(), fill_value=0)  # Ensure all villages are included
)

# Sort service_counts based on city names
service_counts_sorted = service_counts.sort_index(ascending=True)

print(service_counts_sorted)

# Convert the counts into a DataFrame with village names as columns
services_table = pd.DataFrame([service_counts_sorted.values], columns=service_counts_sorted.index)

# Rename the index to indicate it represents service counts
services_table.index = ['service_count']

# View the final table
print(services_table)

# # Optionally save to CSV or another format
services_table.to_csv('/content/services_table.csv')

# from google.colab import files
# files.download('/content/services_table.csv')

"""# **GTFS FILE**"""

# Path to your GTFS file
gtfs_path = "/content/drive/My Drive/amari_gtfs.zip"

# Read the GTFS data using partridge
feed = ptg.load_feed(gtfs_path, view=None)

# Access the data as individual pandas DataFrames
routes = feed.routes
trips = feed.trips
stops = feed.stops
stop_times = feed.stop_times
calendar = feed.calendar

# Extract the GTFS tables
trips = feed.trips
stop_times = feed.stop_times
stops = feed.stops
calendar = feed.calendar

# List of stops you're interested in
selected_stops = [
    "Agia Foteini", "Agia Paraskevi", "Agios Ioannis", "Amari", "Ano Meros", "Apodoulou",
    "Apostoloi", "Ardaktos", "Chordaki", "Drigies", "Elenes", "Fourfouras", "Genna",
    "Gerakari", "Kalogeros", "Kardaki", "Klisidi", "Kouroutes", "Lampiotes", "Lochria",
    "Mandres", "Meronas", "Mesonisia", "Monastiraki", "Moni Asomaton", "Nithauris",
    "Opsigias", "Pantanassa", "Patsos", "Petrochori", "Platania", "Platanos", "Rizikas",
    "Sata", "Thronos", "Vathiaki", "Vistagi", "Vizari", "Voliones", "Vrises"
]

# Join stop_times with stops to get stop names
stop_times_with_names = stop_times.merge(stops[['stop_id', 'stop_name']], on='stop_id', how='left')
stop_times_with_names = stop_times_with_names[['trip_id', 'stop_id', 'stop_sequence', 'stop_name']]

# Filter for selected stops
filtered_stop_times = stop_times_with_names[stop_times_with_names['stop_name'].isin(selected_stops)]

# Self-join to get Origin-Destination pairs for each trip
od_pairs = filtered_stop_times.merge(
    filtered_stop_times,
    on='trip_id',
    suffixes=('_origin', '_destination')
)
# Ensure the origin stop comes before the destination stop in sequence
od_pairs = od_pairs[od_pairs['stop_sequence_origin'] < od_pairs['stop_sequence_destination']]

# Join with trips and calendar data to get service information
od_with_service = od_pairs.merge(trips, on='trip_id', how='left').merge(calendar, on='service_id', how='left')

# Summarize weekly trips between the selected stops
od_weekly = od_with_service.groupby(['stop_name_origin', 'stop_name_destination']).agg(
    weekly_trips=pd.NamedAgg(
        column='monday',
        aggfunc=lambda x: x.sum() + od_with_service['tuesday'].sum() +
                          od_with_service['wednesday'].sum() + od_with_service['thursday'].sum() +
                          od_with_service['friday'].sum()
    )
).reset_index()

# Calculate weekly trips by summing the days of the week for each O-D pair
od_with_service['weekly_trips'] = od_with_service[['monday', 'tuesday', 'wednesday', 'thursday', 'friday']].sum(axis=1)
od_weekly = od_with_service.groupby(['stop_name_origin', 'stop_name_destination'], as_index=False)['weekly_trips'].sum()

# Ensure there are no missing values
od_weekly['weekly_trips'] = od_weekly['weekly_trips'].fillna(0)

# Step 1: Create all possible O-D pairs (including self-pairs)
all_od_pairs = pd.DataFrame(itertools.product(selected_stops, selected_stops), columns=['stop_name_origin', 'stop_name_destination'])

# Step 2: Left join the summarized weekly trips to the full set of O-D pairs
od_complete = all_od_pairs.merge(od_weekly, on=['stop_name_origin', 'stop_name_destination'], how='left')
od_complete['weekly_trips'] = od_complete['weekly_trips'].fillna(0)  # Set missing trips to 0

# Step 3: Create a symmetric matrix for each O-D pair

# Merge od_complete with itself to get forward and reverse pairs
od_symmetric = pd.merge(
    od_complete,
    od_complete,
    left_on=["stop_name_origin", "stop_name_destination"],
    right_on=["stop_name_destination", "stop_name_origin"],
    suffixes=('_forward', '_reverse'),
    how='outer'
)

# Fill NaN values in the trip columns with 0 for both directions
od_symmetric['weekly_trips_forward'] = od_symmetric['weekly_trips_forward'].fillna(0)
od_symmetric['weekly_trips_reverse'] = od_symmetric['weekly_trips_reverse'].fillna(0)

# Sum the trips in both directions
od_symmetric['weekly_trips'] = od_symmetric['weekly_trips_forward'] + od_symmetric['weekly_trips_reverse']

# Select the original columns plus the new forward and reverse columns
od_symmetric = od_symmetric[[ 'stop_name_origin_forward', 'stop_name_destination_forward',  'weekly_trips']]

od_symmetric = od_symmetric.rename(columns={
    'stop_name_origin_forward': 'stop_name_origin',
    'stop_name_destination_forward': 'stop_name_destination'
})

# Step 4: Pivot to create the O-D matrix in wide format, ensuring correct row/column order
od_matrix_symmetric = od_symmetric.pivot(index='stop_name_origin', columns='stop_name_destination', values='weekly_trips').fillna(0)
od_matrix_symmetric = od_matrix_symmetric.reindex(index=selected_stops, columns=selected_stops, fill_value=0).reset_index()

# Assuming od_matrix_symmetric has a column 'stop_name_origin' as the first column
# Remove the first column (stop names) and convert the DataFrame to a NumPy matrix
stop_names = od_matrix_symmetric['stop_name_origin']  # Extract the stop names
od_matrix = od_matrix_symmetric.iloc[:, 1:].to_numpy()  # Convert remaining columns to NumPy array

# Set the diagonal elements to 5
np.fill_diagonal(od_matrix, 5)

# Set all values in the matrix that exceed 5 to exactly 5
od_matrix = np.minimum(od_matrix, 5)

# Convert the modified matrix back to a DataFrame, with the stop names as the first column
od_matrix_symmetric = pd.DataFrame(od_matrix, columns=od_matrix_symmetric.columns[1:])
od_matrix_symmetric.insert(0, 'stop_name', stop_names)  # Add stop names as the first column

pd.options.display.max_columns = None
print(od_matrix_symmetric)

"""# **ACCESSIBILITY CALCULATION**"""

# Load the land uses CSV file
landuses = service_counts_sorted

# # Transpose the land uses table
#landuses_transposed = landuses.T

# Assuming od_matrix_symmetric is a DataFrame loaded or created previously,
# convert it to a matrix excluding the first column if it contains non-numeric data
freq = od_matrix_symmetric.iloc[:, 1:].values  # Adjust if needed

# Flatten the transposed land uses matrix into a vector
Uses = landuses.values.flatten()

# Calculate the sum-product of freq and Uses
sumproduct = np.dot(freq, Uses)

# Convert sumproduct to a DataFrame
Access_Final = pd.DataFrame(sumproduct, columns=["Accessibility"])

# Display the final accessibility DataFrame
print(Access_Final)

# # Save to CSV if needed
# Access_Final.to_csv('/content/Access_Final.csv', index=False)

# Assuming 'df' is your pandas DataFrame
landuses.to_csv('landuses.csv', index=False)  # 'index=False' prevents saving the index as a column

pd.options.display.max_columns = None
print(landuses)

# Ensure freq is a 2D array
freq = od_matrix_symmetric.iloc[:, 1:].values  # Exclude the first column if it's non-numeric

# Flatten the transposed land uses matrix into a vector
Uses = landuses.values.flatten()

# Check shape compatibility
print("Shape of freq:", freq.shape)
print("Length of Uses:", Uses.shape)

# Perform the dot product
sumproduct = np.dot(freq, Uses)

# Ensure the result is 2D for creating a DataFrame
sumproduct = sumproduct.reshape(-1, 1)  # Only needed if sumproduct is not 1D

# Convert sumproduct to a DataFrame
Access_Final = pd.DataFrame(sumproduct, columns=["Accessibility"])

# Display the final accessibility DataFrame
print(Access_Final)

# Check that city_centers is sorted
city_centers_sorted = city_centers.sort_values(by="name_en", ascending=True)

# Create a copy of Access_Final_settl
Access_Final_settl = Access_Final.copy()

# Add pop of city_centers table
Access_Final_settl['pop'] = city_centers_sorted['pop_2021'].values

# Add 'TOP_KOIN' keeping the sorting of names
Access_Final_settl['TOP_KOIN'] = city_centers_sorted['TOP_KOIN'].values

# Print final table
print(Access_Final_settl)

#Remove Prefix of community names
Access_Final_settl['TOP_KOIN'] = Access_Final_settl['TOP_KOIN'].str.replace("Topiki Koinotita ", "", regex=False).str.strip()

# Replace "’" with "A"
Access_Final_settl['TOP_KOIN'] = (
    Access_Final_settl['TOP_KOIN']
    .str.replace("Topiki Koinotita ", "", regex=False)  # Remove text
    .str.replace("’", "A", regex=False)  # Replace text
)

# Print new dataframe
print(Access_Final_settl)

# Save Access_oikismoi to CSV
Access_Final_settl.to_csv('/content/Access_Final_settl.csv', index=False)

# Calculate population-weighted accessibility for each community
community_accessibility = Access_Final_settl.groupby('TOP_KOIN').apply(
    lambda x: pd.Series({
        'total_population': x['pop'].sum(),
        'weighted_accessibility': (x['Accessibility'] * x['pop']).sum() / x['pop'].sum()
    })
).reset_index()

# Add an 'id' column to community_accessibility
community_accessibility['id'] = range(1, len(community_accessibility) + 1)

# Display the results
print(community_accessibility)

# Save Access_oikismoi to CSV
community_accessibility.to_csv('/content/community_accessibility.csv', index=False)